# Server related config
server:
  port: 9094

# Oracle settings
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notesapp?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dMu@469uge*1991
#  url: jdbc:mysql://127.0.0.1:3304/notesapp?useSSL=false
#  username: appuser
#  password: appuser

  #    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
