# Server related config
server:
  port: 9094

# Oracle settings
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notesapp?useSSL=false&allowPublicKeyRetrieval=true
    username: appuser
    password: appuser

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
